version: '3.8'

services: 
  server:
    build: 
      context: .
      dockerfile: ./DockerFile
      target: base
    volumes: 
      - ./src:/home/node/app/src
    container_name: monster-creation-server
    expose: 
      - '4000'
    ports: 
      - '4000:4000'
    command: npm run dev