FROM node:20 as base

WORKDIR /home/node/app

COPY package*.json ./

FROM base as test

RUN npm ci

COPY . .

CMD ["npm", "run", "test"]

FROM base as production

RUN npm ci --production

COPY . .

CMD ["node", "build/server.js"]

ENV NODE_PATH = ./build

RUN npm run build