FROM node:20 as base

WORKDIR /home/node/app

COPY package*.json ./

FROM base as test
ENV NODE_ENV=development
RUN npm install --include=dev
COPY . .
RUN npm run test

FROM base as production
ENV NODE_ENV=production
RUN npm ci --production
COPY . .
CMD ["node", "build/server.js"]

ENV NODE_PATH = ./build

RUN npm run build